name: tests
on: push
jobs:
  installDependencies:
    name: Run Linter, and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - name: Linter
        run: npm run lint